Fix issue with deprecated boost::filesystem::ifstream
Building is failing with the following error when linking with Boost
1.79:

src/libaktualizr/uptane/fetcher.cc:34:22: error: 'ifstream' is not a
member of 'boost::filesystem'; did you mean 'std::ifstream'?

This is because boost 1.79 deprecated boost::filesystem::ofstream.
Change it to use std::ifstream.

Related-to: TOR-2421

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>