Include missing fstream header
Build with latest gcc versions fails with the following error:

error: variable 'std::ifstream as' has initializer but incomplete type

Fix it by including missing fstream header.

Related-to: TOR-2421

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>